// <auto-generated />
using FallGuyStats.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FallGuyStats.Migrations
{
    [DbContext(typeof(EpisodeContext))]
    [Migration("20200830055625_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("FallGuyStats.Models.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Crowns")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fame")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kudos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("FallGuyStats.Models.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Badge")
                        .HasColumnType("TEXT");

                    b.Property<int>("BonusFame")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusKudos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusTier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fame")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kudos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Qualified")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
