// <auto-generated />
using System;
using FallGuyStats.Data;
using FallGuyStats.Objects.Models.Views;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FallGuyStats.Migrations
{
    [DbContext(typeof(StatContext))]
    partial class StatContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity<TodayStatsView>(b =>
            {
                b.HasKey(e => new { e.EpisodeFinishedDate });
                b.ToView("vTodayStats"); 
                b.Property<int>("Season").HasColumnType("INTEGER");
                b.Property<DateTime>("EpisodeFinishedDate").HasColumnType("DATE");
                b.Property<int>("EpisodeCount").HasColumnType("INTEGER");
                b.Property<int>("CrownCount").HasColumnType("INTEGER");
                
            });

            modelBuilder.Entity<SeasonStatsView>(b =>
            {
                b.HasKey(e => e.Season);
                b.ToView("vSessionStats"); b.Property<int>("Season").HasColumnType("INTEGER");
                b.Property<DateTime>("EpisodeFinishedDate").HasColumnType("DATE");
                b.Property<int>("EpisodeCount").HasColumnType("INTEGER");
                b.Property<int>("CrownCount").HasColumnType("INTEGER");
                
            });
#pragma warning restore 612, 618
        }
    }
}
